language: generic 
sudo: required
services:
 - docker

before_install:
  - docker build -t rsv7/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rsv7/react-test npm test

after_success:
 - docker build -t rsv7/multi-client ./client
 - docker build -t rsv7/multi-nginx ./nginx
 - docker build -t rsv7/multi-server ./server
 - docker build -t rsv7/multi-worker ./worker
 # Login to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # Take those images and push them to docker hub
 - docker push rsv7/multi-client 
 - docker push rsv7/multi-nginx 
 - docker push rsv7/multi-server 
 - docker push rsv7/multi-worker 
